import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

import PP2 from './page2'
import A3 from './page3'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Playstation',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        
      <body className={inter.className}>
        
           <header>
            <nav className='  h-20 sm:w-screen flex  items-center  gap-10 text-4xl g justify-center md:justify-around '
            style={{color: "#2b2d42"}}
             >

                <div className='flex  items-center  gap-10 text-4xl g justify-start '>
                  <img  className='md:w-[60px]  mx-10  w-[40px] hover:scale-125 transition-all ease-in-out' src=
                  "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/PlayStation_logo.svg/2560px-PlayStation_logo.svg.png" alt="" />
                </div>

              <div className='flex justify-center items-center gap-10 text-[1.3rem] md:text-[2.3rem]'>
                <Link href="./"className='bg hover:text-cyan-500 transition-all ease-in-out hover:scale-125'>
                  <h1>Home</h1></Link>

                <Link href="./Shop"className='bg hover:text-cyan-500 transition-all ease-in-out hover:scale-125'>
                  <h1>Games</h1></Link>
                  
                  <Link href="./Contact"className='bg hover:text-cyan-500 transition-all ease-in-out hover:scale-125'>
                  <h1>Contact</h1></Link>
              </div>
                
               
            </nav>
           </header>
           
       { children }
        
      </body>
    </html>
  )
}
